buildscript {
	dependencies {
		classpath 'org.flywaydb:flyway-core:11.13.0'
		classpath 'org.flywaydb:flyway-database-postgresql:11.13.0'
	}
}

plugins {
	id 'idea'
	id 'java'
	id 'org.springframework.boot' version '3.5.9'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.springframework.cloud.contract' version '4.3.3'
	id 'org.flywaydb.flyway' version '11.13.0'
}

group = 'com.github.rhafaelcosta.commerce'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
	mockitoAgent
}

repositories {
	mavenCentral()
}

ext {
	set('springCloudVersion', "2025.0.2")
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	implementation 'org.flywaydb:flyway-core'
	implementation 'org.modelmapper:modelmapper:3.2.4'
	implementation 'org.flywaydb:flyway-database-postgresql'
	implementation 'commons-validator:commons-validator:1.9.0'
	implementation 'io.hypersistence:hypersistence-tsid:2.1.4'
	implementation 'com.fasterxml.uuid:java-uuid-generator:5.1.0'

	testImplementation 'io.rest-assured:rest-assured'
	testImplementation 'io.rest-assured:spring-mock-mvc'
	testImplementation 'org.assertj:assertj-core:3.27.3'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.cloud:spring-cloud-starter-contract-verifier'
	testImplementation 'org.springframework.cloud:spring-cloud-starter-contract-stub-runner'


	testImplementation 'org.springframework.boot:spring-boot-testcontainers'
	testImplementation 'org.testcontainers:junit-jupiter'
	testImplementation 'org.testcontainers:postgresql'

//	runtimeOnly 'com.h2database:h2'
	runtimeOnly 'org.postgresql:postgresql'

	compileOnly 'org.projectlombok:lombok'

	annotationProcessor 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	mockitoAgent('org.mockito:mockito-core:5.14.2') {transitive = false}
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

contracts {
	packageWithBaseClasses = "com.github.rhafaelcosta.commerce.order.contract.base"
}

test {
	filter {
		excludeTestsMatching("*IT")
	}
	jvmArgs += "-javaagent:${configurations.mockitoAgent.asPath}"
}

tasks.named('test') {
	useJUnitPlatform()
}

tasks.named('check') {
	dependsOn(test, contractTest, integrationTest)
}

tasks.named('contractTest') {
	useJUnitPlatform()
}

tasks.register('integrationTest', Test) {
	description = 'Run integration tests.'
	group = 'verification'

	jvmArgs += "-javaagent:${configurations.mockitoAgent.asPath}"

	testClassesDirs = sourceSets.test.output.classesDirs
	classpath = sourceSets.test.runtimeClasspath

	shouldRunAfter test

	useJUnitPlatform()

	testLogging {
		events "passed"
	}

	filter {
		includeTestsMatching "*IT"
		excludeTestsMatching "*Test"
	}
}

bootJar {
	archiveFileName = "order-service.jar"
}

tasks.register('dockerBuild', Exec) {
	description = 'Builds a multi-platform Docker image using Buildx'
	group = 'build'
	dependsOn('bootJar')
	workingDir project.rootDir
	commandLine 'docker', 'buildx', 'build', '--platform', 'linux/arm64/v8,linux/amd64',
			'--tag', 'commerce/order-service:dev', '.'
}