spring:
    datasource:
        url: jdbc:postgresql://commerce-postgres:5432/ordering

    flyway:
        enabled: true
        locations: classpath:db/migration,classpath:db/testdata
        url: jdbc:postgresql://commerce-postgres:5432/ordering

commerce-platform:
    integrations:
        shipping.provider: RAPIDEX
        rapidex.url: http://wiremock:8080
        product-catalog.url: http://wiremock:8080