spring:
    application:
        name: order-service

    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false

    flyway:
        enabled: false
        locations: classpath:db/migration

commerce-platform:
    integrations:
        shipping.provider: RAPIDEX